---
# Ansible快速入门案例
- hosts: all
  tasks:
    - name: 导入 Remi GPG 密钥
      rpm_key: "key={{ item }} state=present"
      with_items:
        - "http://rpms.famillecollet.com/RPM-GPG-KEY-remi"
    - name: Install Remi repo.
      command: "rpm -Uvh --force {{ item.href }} creates={{ item.creates }}"
      with_items:
        - href: "http://rpms.famillecollet.com/enterprise/remi-release-6.rpm"
          creates: "/etc/yum.repos.d/remi.repo"
    - name: 安装Remi源
      yum: name=epel-release state=present
    - name: 关闭防火墙
      service: name=iptables state=stopped
    - name: 安装NodeJS和npm
      yum: name=npm state=present enablerepo=epel
    - name: 使用Taobao的npm源
      command: >
        npm config set registry https://registry.npm.taobao.org
    - name: 关闭npm的https
      command: >
        npm config set strict-ssl false
    - name: 安装Forever(用于启动Node.js app)
      npm: name=forever global=yes state=latest
    - name: 确保 Node.js app的目录存在
      file: "path={{ node_apps_location }} state=directory"
    - name: 复制Node.js app整个目录到目标主机
      copy: "src=app dest={{ node_apps_location }}"
    - name: 安装package.json文件中定义的依赖关系
      npm: "path={{ node_apps_location }}/app"
    - name: 获取正在运行的Node.js app列表
      command: forever list
      register: forever_list
      changed_when: false
    - name: 启动Node.js app
      command: "forever start {{ node_apps_location }}/app/app.js"
      when: "forever_list.stdout.find('{{ node_apps_location }}/app/app.js') == -1"