---
# 可以给整个Playbook的所有任务打一个标签
- hosts: apps
  tags: deploy
  # roles:
  #   # 给角色打的标签将会应用于角色下所有的任务
  #   - { role: tomcat, tags: ['tomcat', 'app'] }
  tasks:
    - name: Notify on completion.
      local_action:
        module: osx_say
        msg: "{{ inventory_hostname }} is finished!"
        voice: Zarvox
      tags:
        - notifications
        - say

    - include_tasks: tags.yml
      tags: foo